### PR TITLE
Document settings reset on MD-9600.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
LOL.

OK. I had forgotten this was on P3 not P1

I wonder why we can't use P1, I presume there is some clash with entering the bootloader on bootup ?

**Comment by f1rmb** [comment]
Well, back then, I've made a lot of tests, and the P1/P2 is not usable when booting, yes, probably because of the bootloader (and in one case, IIRC, you have to remove the power otherwise you're stuck).

**Comment by rogerclarkmelbourne** [comment]
OK. That makes sense

**Comment by f1rmb** [comment]
BTW, I just noticed that settingsEraseCustomContent() isn't implemented (well, used) on any STM32 platforms (hence the manual is wrong about boot image and melody reset).
I will fix that later today.

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

**Pull request merged**
