### PR TITLE
Fix some broken anchors / typos.

### PR DESCRIPTION
**Pull request by f1rmb**
Use MD-9600, RT-90, MD-UV380 words (380UV is a different beast).
Remove Timezone specific screen (and picture), as it's part of Display Options (and update the explanation). 
Small cleanup of the MD-9600 section (and make the picture to fit the page).
Update picture with white background to match the reality (and the other pictures). 
Update Timeout picture (it was really outdated).
PDF updated as well.

**NOTE**: The calibration section isn't accurate/finished, but the code hasn't been merged yet.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold on a second I still have a problem with one anchor between PDF and MD version.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by f1rmb** [comment]
Okay, I will raise another PR for the problematic anchor ;-)

**Comment by rogerclarkmelbourne** [comment]
OK. I didnt notice it.

**Comment by f1rmb** [comment]
No worry, that specific anchor wasn't working before ;-)

**Pull request merged**
