### PR TITLE
Synchronize Chinese version User Guide translation

### PR DESCRIPTION
**Pull request by Misaka13514**
Still WIP...
I'll squash my commits into one when I'm finished.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
This PR has conflicts after I merged your previous PR

**Comment by rogerclarkmelbourne** [comment]
Bump....

Can you update the chinese with the latest changes from the English version. ???

**Comment by Misaka13514** [comment]
ok, although I am busy preparing for the college entrance exam these days, I will finish this translation as soon as possible. (But it still takes a while)

**Comment by rogerclarkmelbourne** [comment]
Thank you.

**Comment by Misaka13514** [comment]
Content is fully translated.

Formatting and proofreading are still required.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
Thank you

**Comment by Misaka13514** [comment]
The translations are already done, I have requested BH4ESK to proofread these translations, so it may take a few more days to complete the work.

**Comment by rogerclarkmelbourne** [comment]
Is the PR ready to merge now ?

**Comment by Misaka13514** [comment]
@michae1eo wants to check again tonight, but I think it LGTM.
We will notify you when it is ready to merge.

If you merge the PR now, we will create a new PR if more changes are needed.

**Comment by rogerclarkmelbourne** [comment]
Its OK.

I will wait until it is checked again

**Comment by michae1eo** [comment]
Hei everyone! It's been a long time isn't it?
Yes the translation can be merge now, I've done checking and since development is actively going I would say this version is good enough for now.🧐

Thanks for @Misaka13514 providing translation.🤗
And @rogerclarkmelbourne may I reupload the new translated manual to one of the Chinese ham forum hellocq.net once merged?

**Comment by Misaka13514** [comment]
Thank you @michae1eo for your careful and perfect proofreading and revision of my translation, you really did a great job.

@rogerclarkmelbourne Sorry to keep you waiting for so long time.

**Comment by rogerclarkmelbourne** [comment]
Ok.

Thank you

**Pull request merged**
