### PR TITLE
Document "RX Beep" and "Talker" Sound options.

### PR DESCRIPTION
**Pull request by f1rmb**
Just noticed these missing ones.

### CODE REVIEW

**Comment by f1rmb** [comment]
Hold on a second. I just noticed something else.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks

**Comment by rogerclarkmelbourne** [comment]
Too late, I already merged it :-(

**Comment by f1rmb** [comment]
LOL

**Comment by f1rmb** [comment]
I raised a new PR, it's about CC Filter -> CC scan renaming.

**Comment by rogerclarkmelbourne** [comment]
OK.

I saw it, but did not want to process it too quickly, in case you were still working on it

**Comment by f1rmb** [comment]
;-)

Well, I will try to sleep a bit more now, so don't expect much in the next hours :-D

**Comment by rogerclarkmelbourne** [comment]
OK. No worries

**Pull request merged**
