### PR TITLE
update translation to 1a2d74d

### PR DESCRIPTION
**Pull request by IsayIsee**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Will you also translate the new APRS Tx functionality ?

**Comment by IsayIsee** [comment]
> 

No problem, I am currently building an environment for generating PDF

**Comment by rogerclarkmelbourne** [comment]
BTW. Its best not to keep commit just to see your changes.  

Notepad++ has a markup viewer plugin which is one way to view and check the markup, albeit does not view images

**Comment by IsayIsee** [comment]
> BTW. Its best not to keep commit just to see your changes.
> 
> Notepad++ has a markup viewer plugin which is one way to view and check the markup, albeit does not view images

Thank you for your suggestion, habits by coding.

**Comment by rogerclarkmelbourne** [comment]
Have you now finished your updates ?

Ideally, don't raise a PR until you have finished, otherise I may end up merging before you finish

**Comment by IsayIsee** [comment]
yes i finished updates. the reason for updating after submitting PR is to translate the latest updates as well

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks. I will merge it later today

**Pull request merged**
