### PR TITLE
Fix formatting of the satellites.txt table.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

What was the problem with the table format ?

**Comment by f1rmb** [comment]
Hi Roger, 

Well the biggest problem was the column formatting, many rows had mismatching number of columns, plus a space at the end.

**Comment by rogerclarkmelbourne** [comment]
Ah 

OK.

I cut and pasted from satellites.txt and searched and replaced , with |  and then manually added a | at the end, hence I thought it should have the correct number of columns, but obviously not.
I also didn't check for spaces at the end, because I presumed white-space was ignored.

**Comment by f1rmb** [comment]
Okay.
About spaces at the end of a line, there are some tricks using it, which turns it as a hidden problem sometimes...

As you probably noticed, I splitted "ArmCTCSS" word in the header, as it turned out that the PDF rendering was really bad.

**Pull request merged**
